import { ARTICLE_CONTENT } from "../../../blog/midjourney-film-photo-prompts/content";

export const metadata = { title: "블로그 수정 | Consolve Admin", robots: { index: false, follow: false } };
const css = `@import url('https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable.css');*{box-sizing:border-box}body{margin:0;font-family:"Pretendard","Noto Sans KR",system-ui,sans-serif;background:#f7f7f8;color:#111114;letter-spacing:-.02em}.wrap{max-width:1040px;margin:0 auto;padding:56px 24px 96px}.top{display:flex;justify-content:space-between;gap:16px;align-items:center;margin-bottom:28px}.badge{display:inline-flex;border:1px solid #dfddff;background:#f0efff;color:#5148df;border-radius:999px;padding:7px 12px;font-size:13px;font-weight:800}h1{font-size:42px;line-height:1.15;letter-spacing:-.055em;margin:12px 0 8px}.muted{color:#666b74;margin:0;line-height:1.7}.card{background:#fff;border:1px solid #ececf0;border-radius:24px;padding:26px;box-shadow:0 16px 54px rgba(0,0,0,.06)}label{display:block;font-weight:800;margin:20px 0 8px}input,textarea{width:100%;border:1px solid #dddfe6;border-radius:16px;padding:14px 16px;font:inherit;line-height:1.5;background:#fff;outline:none}textarea{min-height:100px;resize:vertical}.json-editor{min-height:620px;font-family:"SFMono-Regular",Consolas,monospace;font-size:13px;line-height:1.6;white-space:pre}.actions{display:flex;gap:10px;align-items:center;margin-top:24px;flex-wrap:wrap}.btn{display:inline-flex;align-items:center;justify-content:center;height:44px;border-radius:999px;padding:0 18px;font-weight:850;border:1px solid #d9dbe3;background:#fff;color:#222;text-decoration:none;cursor:pointer}.btn.primary{border:0;background:#111114;color:#fff}.btn:disabled{opacity:.55;cursor:not-allowed}.status{margin-top:18px;border-radius:16px;padding:14px 16px;display:none;white-space:pre-wrap;line-height:1.6}.status.ok{display:block;background:#effaf3;color:#11632b;border:1px solid #bfebcd}.status.err{display:block;background:#fff0f0;color:#a01818;border:1px solid #f1c5c5}.hint{font-size:13px;color:#7b8088;margin-top:16px;line-height:1.7}.fields{margin-top:24px}.back{color:#5148df;text-decoration:none;font-weight:800}.quick{display:grid;grid-template-columns:1fr 1fr;gap:14px}.quick textarea{min-height:90px}@media(max-width:760px){.top{align-items:flex-start;flex-direction:column}.quick{grid-template-columns:1fr}h1{font-size:34px}.card{padding:20px}}`;

export default function EditPromptArticlePage() {
  const articleJson = JSON.stringify(ARTICLE_CONTENT, null, 2);
  return (
    <>
      <style dangerouslySetInnerHTML={{ __html: css }} />
      <main className="wrap">
        <div className="top"><div><span className="badge">Admin only</span><h1>블로그 전체 수정</h1><p className="muted">제목/요약뿐 아니라 본문 문단, 옵션 표, 프롬프트 10개, 체크리스트까지 전체 JSON으로 수정합니다. 저장하면 GitHub main에 커밋되어 Vercel 자동배포가 트리거됩니다.</p></div><a className="back" href="/blog/midjourney-film-photo-prompts">글 보기 →</a></div>
        <section className="card"><form id="editForm"><input type="hidden" name="slug" defaultValue={ARTICLE_CONTENT.slug} /><div className="fields">
          <div className="quick"><div><label htmlFor="title">제목</label><input id="title" name="title" defaultValue={ARTICLE_CONTENT.title} required maxLength={100} /></div><div><label htmlFor="excerpt">블로그 목록 요약</label><textarea id="excerpt" name="excerpt" defaultValue={ARTICLE_CONTENT.excerpt} required maxLength={240} /></div></div>
          <label htmlFor="description">SEO 설명</label><textarea id="description" name="description" defaultValue={ARTICLE_CONTENT.seoDescription} required maxLength={320} />
          <label htmlFor="lead">상단 리드 문장</label><textarea id="lead" name="lead" defaultValue={ARTICLE_CONTENT.lead} required maxLength={400} />
          <label htmlFor="contentJson">전체 본문 JSON</label><textarea id="contentJson" name="contentJson" className="json-editor" defaultValue={articleJson} spellCheck={false} required />
        </div><div className="actions"><button className="btn primary" type="submit">전체 저장하고 배포 요청</button><button className="btn" type="button" id="syncQuick">위 빠른 필드 → JSON 반영</button><a className="btn" href="/blog">목록으로</a></div><p className="hint">본문 JSON에서 introParagraphs, note, options, promptItems, howToItems, checklist, outro를 수정하면 공개 글 전체가 바뀝니다. 코드 표기는 백틱(`code`), 굵게는 **텍스트**로 쓸 수 있습니다.</p><div id="status" className="status" role="status" aria-live="polite" /></form></section>
      </main>
      <script dangerouslySetInnerHTML={{ __html: `(() => { const form=document.querySelector('#editForm'); const status=document.querySelector('#status'); const button=form?.querySelector('button[type="submit"]'); const syncButton=document.querySelector('#syncQuick'); const contentJson=document.querySelector('#contentJson'); const setStatus=(type,message)=>{status.className='status '+type;status.textContent=message;}; const applyQuickFields=()=>{const article=JSON.parse(contentJson.value); article.title=document.querySelector('#title').value.trim(); article.seoDescription=document.querySelector('#description').value.trim(); article.lead=document.querySelector('#lead').value.trim(); article.excerpt=document.querySelector('#excerpt').value.trim(); contentJson.value=JSON.stringify(article,null,2); return article;}; if(!form||!status||!button||!contentJson)return; syncButton?.addEventListener('click',()=>{try{applyQuickFields();setStatus('ok','빠른 필드를 전체 JSON에 반영했습니다.');}catch(error){setStatus('err','JSON 형식 오류: '+error.message);}}); form.addEventListener('submit',async(event)=>{event.preventDefault();button.disabled=true;status.className='status';status.textContent='';try{const article=applyQuickFields();const response=await fetch('/api/admin/blog/midjourney-film-photo-prompts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({article})});const data=await response.json().catch(()=>({}));if(!response.ok||!data.ok)throw new Error(data.error||'저장에 실패했습니다.');setStatus('ok','저장 커밋 완료: '+(data.commit||'변경 없음')+'\nVercel 자동배포가 시작됩니다.');}catch(error){setStatus('err',error.message||String(error));}finally{button.disabled=false;}}); })();` }} />
    </>
  );
}
